#!/bin/bash
lz5manage --stop
service influxdb stop
rm -rf /var/lib/influxdb/data/lz5*
rm -rf /var/lib/influxdb/wal/lz5*
service influxdb start
while ! curl -k http://localhost:8086/ping 2> /dev/null
do
    echo "Waiting for Influx..."
    sleep 1
done
sleep 2
curl -POST http://localhost:8086/query --data-urlencode "q=CREATE DATABASE lz5results" >/dev/null 2>&1
curl -POST http://localhost:8086/query --data-urlencode "q=CREATE DATABASE lz5aggregates" >/dev/null 2>&1
curl -POST http://localhost:8086/query --data-urlencode "q=CREATE DATABASE lz5rusage" >/dev/null 2>&1
lz5setup --armageddon=kaboom --db-root-pass "LZ.$(hostid)"
lz5configmanager -si DEDUP_WINDOW 3600
lz5configmanager -ss LOG_MAX_LEVEL INFO
rm /var/lib/logzilla/scripts/*
cp ../LogZilla-Files/automations/* /var/lib/logzilla/scripts/
chown -R logzilla:logzilla /var/lib/logzilla/scripts/
read -p "Shall I start LogZilla? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    lz5manage --start
fi
sleep 5

lz5dashboards import -I ../LogZilla-Files/dashboards/ciscolive-dashboards.json
lz5triggers import -I ../LogZilla-Files/triggers/ciscolive-triggers.json
